//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

using System.Xml.Serialization;

namespace SxSPro.Schema {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    [XmlRoot(Namespace="", IsNullable=false)]
    public partial class XmlRoot {
        
        private XmlRootSummary summaryField;
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlRootSummary Summary {
            get {
                return this.summaryField;
            }
            set {
                this.summaryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class XmlRootSummary {
        
        private XmlRootSummaryWinRiver_II_Section_by_Section_Summary winRiver_II_Section_by_Section_SummaryField;
        
        private XmlRootSummaryStation[] stationField;
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlRootSummaryWinRiver_II_Section_by_Section_Summary WinRiver_II_Section_by_Section_Summary {
            get {
                return this.winRiver_II_Section_by_Section_SummaryField;
            }
            set {
                this.winRiver_II_Section_by_Section_SummaryField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("Station", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public XmlRootSummaryStation[] Station {
            get {
                return this.stationField;
            }
            set {
                this.stationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class XmlRootSummaryWinRiver_II_Section_by_Section_Summary {
        
        private string site_NameField;
        
        private string printed_DateField;
        
        private string station_NoField;
        
        private string air_TempField;
        
        private string water_TempField;
        
        private string river_NameField;
        
        private string locationField;
        
        private string dateField;
        
        private string start_End_TimeField;
        
        private string partyField;
        
        private string software_VerField;
        
        private string units_of_MeasureField;
        
        private string meas_NoField;
        
        private string no_StationsField;
        
        private string q_MethodField;
        
        private string vel_MethodField;
        
        private string referenceField;
        
        private decimal power_ExpField;
        
        private bool power_ExpFieldSpecified;
        
        private decimal left_CoeffField;
        
        private bool left_CoeffFieldSpecified;
        
        private decimal right_CoeffField;
        
        private bool right_CoeffFieldSpecified;
        
        private string durationField;
        
        private string instrumentField;
        
        private string firmware_VersionField;
        
        private string water_ModeField;
        
        private decimal aDCP_DepthField;
        
        private bool aDCP_DepthFieldSpecified;
        
        private decimal blankField;
        
        private bool blankFieldSpecified;
        
        private string num_CellsField;
        
        private string cell_SizeField;
        
        private decimal total_QField;
        
        private bool total_QFieldSpecified;
        
        private decimal meas_AreaField;
        
        private bool meas_AreaFieldSpecified;
        
        private decimal mean_VelField;
        
        private bool mean_VelFieldSpecified;
        
        private decimal meas_WidthField;
        
        private bool meas_WidthFieldSpecified;
        
        private decimal max_VelField;
        
        private bool max_VelFieldSpecified;
        
        private decimal max_DepthField;
        
        private bool max_DepthFieldSpecified;
        
        private decimal quality_ControlField;
        
        private bool quality_ControlFieldSpecified;
        
        private decimal meas_AngleField;
        
        private bool meas_AngleFieldSpecified;
        
        private decimal stageField;
        
        private bool stageFieldSpecified;
        
        private decimal rated_QField;
        
        private bool rated_QFieldSpecified;
        
        private string begin_ShoreField;
        
        private string aDCP_Serial_NoField;
        
        private string rawFileNameField;
        
        private string configFileNameField;
        
        private string software_VersionField;
        
        private string system_FrequencyField;
        
        private string commentsField;
        
        private string flowTypeField;
        
        private string footNoteField;
        
        private string contourFileField;
        
        private decimal total_WidthField;
        
        private bool total_WidthFieldSpecified;
        
        private decimal total_AreaField;
        
        private bool total_AreaFieldSpecified;
        
        private decimal total_Slush_AreaField;
        
        private bool total_Slush_AreaFieldSpecified;
        
        private decimal totalPerc__SlushField;
        
        private bool totalPerc__SlushFieldSpecified;
        
        private string total_Start_TField;
        
        private decimal mean_DepthField;
        
        private bool mean_DepthFieldSpecified;
        
        private decimal mean_CVField;
        
        private bool mean_CVFieldSpecified;
        
        private decimal mean_Avg_VField;
        
        private bool mean_Avg_VFieldSpecified;
        
        private decimal mean_Dir_VField;
        
        private bool mean_Dir_VFieldSpecified;
        
        private decimal mean_ADCP_DepthField;
        
        private bool mean_ADCP_DepthFieldSpecified;
        
        private decimal mean_Solid_Ice_ThicknessField;
        
        private bool mean_Solid_Ice_ThicknessFieldSpecified;
        
        private decimal mean_WS_Btm_Of_IceField;
        
        private bool mean_WS_Btm_Of_IceFieldSpecified;
        
        private decimal mean_WS_Btm_Of_SlushField;
        
        private bool mean_WS_Btm_Of_SlushFieldSpecified;
        
        private decimal mean_Meas_TField;
        
        private bool mean_Meas_TFieldSpecified;
        
        private decimal mean_Ang_CfField;
        
        private bool mean_Ang_CfFieldSpecified;
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Site_Name {
            get {
                return this.site_NameField;
            }
            set {
                this.site_NameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Printed_Date {
            get {
                return this.printed_DateField;
            }
            set {
                this.printed_DateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Station_No {
            get {
                return this.station_NoField;
            }
            set {
                this.station_NoField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Air_Temp {
            get {
                return this.air_TempField;
            }
            set {
                this.air_TempField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Water_Temp {
            get {
                return this.water_TempField;
            }
            set {
                this.water_TempField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string River_Name {
            get {
                return this.river_NameField;
            }
            set {
                this.river_NameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Start_End_Time {
            get {
                return this.start_End_TimeField;
            }
            set {
                this.start_End_TimeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Party {
            get {
                return this.partyField;
            }
            set {
                this.partyField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Software_Ver {
            get {
                return this.software_VerField;
            }
            set {
                this.software_VerField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Units_of_Measure {
            get {
                return this.units_of_MeasureField;
            }
            set {
                this.units_of_MeasureField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string Meas_No {
            get {
                return this.meas_NoField;
            }
            set {
                this.meas_NoField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string No_Stations {
            get {
                return this.no_StationsField;
            }
            set {
                this.no_StationsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Q_Method {
            get {
                return this.q_MethodField;
            }
            set {
                this.q_MethodField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Vel_Method {
            get {
                return this.vel_MethodField;
            }
            set {
                this.vel_MethodField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Power_Exp {
            get {
                return this.power_ExpField;
            }
            set {
                this.power_ExpField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Power_ExpSpecified {
            get {
                return this.power_ExpFieldSpecified;
            }
            set {
                this.power_ExpFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Left_Coeff {
            get {
                return this.left_CoeffField;
            }
            set {
                this.left_CoeffField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Left_CoeffSpecified {
            get {
                return this.left_CoeffFieldSpecified;
            }
            set {
                this.left_CoeffFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Right_Coeff {
            get {
                return this.right_CoeffField;
            }
            set {
                this.right_CoeffField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Right_CoeffSpecified {
            get {
                return this.right_CoeffFieldSpecified;
            }
            set {
                this.right_CoeffFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Instrument {
            get {
                return this.instrumentField;
            }
            set {
                this.instrumentField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Firmware_Version {
            get {
                return this.firmware_VersionField;
            }
            set {
                this.firmware_VersionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Water_Mode {
            get {
                return this.water_ModeField;
            }
            set {
                this.water_ModeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ADCP_Depth {
            get {
                return this.aDCP_DepthField;
            }
            set {
                this.aDCP_DepthField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool ADCP_DepthSpecified {
            get {
                return this.aDCP_DepthFieldSpecified;
            }
            set {
                this.aDCP_DepthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Blank {
            get {
                return this.blankField;
            }
            set {
                this.blankField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool BlankSpecified {
            get {
                return this.blankFieldSpecified;
            }
            set {
                this.blankFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Num_Cells {
            get {
                return this.num_CellsField;
            }
            set {
                this.num_CellsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Cell_Size {
            get {
                return this.cell_SizeField;
            }
            set {
                this.cell_SizeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Total_Q {
            get {
                return this.total_QField;
            }
            set {
                this.total_QField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Total_QSpecified {
            get {
                return this.total_QFieldSpecified;
            }
            set {
                this.total_QFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Meas_Area {
            get {
                return this.meas_AreaField;
            }
            set {
                this.meas_AreaField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Meas_AreaSpecified {
            get {
                return this.meas_AreaFieldSpecified;
            }
            set {
                this.meas_AreaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Mean_Vel {
            get {
                return this.mean_VelField;
            }
            set {
                this.mean_VelField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Mean_VelSpecified {
            get {
                return this.mean_VelFieldSpecified;
            }
            set {
                this.mean_VelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Meas_Width {
            get {
                return this.meas_WidthField;
            }
            set {
                this.meas_WidthField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Meas_WidthSpecified {
            get {
                return this.meas_WidthFieldSpecified;
            }
            set {
                this.meas_WidthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Max_Vel {
            get {
                return this.max_VelField;
            }
            set {
                this.max_VelField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Max_VelSpecified {
            get {
                return this.max_VelFieldSpecified;
            }
            set {
                this.max_VelFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Max_Depth {
            get {
                return this.max_DepthField;
            }
            set {
                this.max_DepthField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Max_DepthSpecified {
            get {
                return this.max_DepthFieldSpecified;
            }
            set {
                this.max_DepthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Quality_Control {
            get {
                return this.quality_ControlField;
            }
            set {
                this.quality_ControlField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Quality_ControlSpecified {
            get {
                return this.quality_ControlFieldSpecified;
            }
            set {
                this.quality_ControlFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Meas_Angle {
            get {
                return this.meas_AngleField;
            }
            set {
                this.meas_AngleField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Meas_AngleSpecified {
            get {
                return this.meas_AngleFieldSpecified;
            }
            set {
                this.meas_AngleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Stage {
            get {
                return this.stageField;
            }
            set {
                this.stageField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool StageSpecified {
            get {
                return this.stageFieldSpecified;
            }
            set {
                this.stageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Rated_Q {
            get {
                return this.rated_QField;
            }
            set {
                this.rated_QField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Rated_QSpecified {
            get {
                return this.rated_QFieldSpecified;
            }
            set {
                this.rated_QFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Begin_Shore {
            get {
                return this.begin_ShoreField;
            }
            set {
                this.begin_ShoreField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ADCP_Serial_No {
            get {
                return this.aDCP_Serial_NoField;
            }
            set {
                this.aDCP_Serial_NoField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RawFileName {
            get {
                return this.rawFileNameField;
            }
            set {
                this.rawFileNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ConfigFileName {
            get {
                return this.configFileNameField;
            }
            set {
                this.configFileNameField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Software_Version {
            get {
                return this.software_VersionField;
            }
            set {
                this.software_VersionField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string System_Frequency {
            get {
                return this.system_FrequencyField;
            }
            set {
                this.system_FrequencyField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Comments {
            get {
                return this.commentsField;
            }
            set {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FlowType {
            get {
                return this.flowTypeField;
            }
            set {
                this.flowTypeField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FootNote {
            get {
                return this.footNoteField;
            }
            set {
                this.footNoteField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContourFile {
            get {
                return this.contourFileField;
            }
            set {
                this.contourFileField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Total_Width {
            get {
                return this.total_WidthField;
            }
            set {
                this.total_WidthField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Total_WidthSpecified {
            get {
                return this.total_WidthFieldSpecified;
            }
            set {
                this.total_WidthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Total_Area {
            get {
                return this.total_AreaField;
            }
            set {
                this.total_AreaField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Total_AreaSpecified {
            get {
                return this.total_AreaFieldSpecified;
            }
            set {
                this.total_AreaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Total_Slush_Area {
            get {
                return this.total_Slush_AreaField;
            }
            set {
                this.total_Slush_AreaField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Total_Slush_AreaSpecified {
            get {
                return this.total_Slush_AreaFieldSpecified;
            }
            set {
                this.total_Slush_AreaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal TotalPerc__Slush {
            get {
                return this.totalPerc__SlushField;
            }
            set {
                this.totalPerc__SlushField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool TotalPerc__SlushSpecified {
            get {
                return this.totalPerc__SlushFieldSpecified;
            }
            set {
                this.totalPerc__SlushFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Total_Start_T {
            get {
                return this.total_Start_TField;
            }
            set {
                this.total_Start_TField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Mean_Depth {
            get {
                return this.mean_DepthField;
            }
            set {
                this.mean_DepthField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Mean_DepthSpecified {
            get {
                return this.mean_DepthFieldSpecified;
            }
            set {
                this.mean_DepthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Mean_CV {
            get {
                return this.mean_CVField;
            }
            set {
                this.mean_CVField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Mean_CVSpecified {
            get {
                return this.mean_CVFieldSpecified;
            }
            set {
                this.mean_CVFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Mean_Avg_V {
            get {
                return this.mean_Avg_VField;
            }
            set {
                this.mean_Avg_VField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Mean_Avg_VSpecified {
            get {
                return this.mean_Avg_VFieldSpecified;
            }
            set {
                this.mean_Avg_VFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Mean_Dir_V {
            get {
                return this.mean_Dir_VField;
            }
            set {
                this.mean_Dir_VField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Mean_Dir_VSpecified {
            get {
                return this.mean_Dir_VFieldSpecified;
            }
            set {
                this.mean_Dir_VFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Mean_ADCP_Depth {
            get {
                return this.mean_ADCP_DepthField;
            }
            set {
                this.mean_ADCP_DepthField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Mean_ADCP_DepthSpecified {
            get {
                return this.mean_ADCP_DepthFieldSpecified;
            }
            set {
                this.mean_ADCP_DepthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Mean_Solid_Ice_Thickness {
            get {
                return this.mean_Solid_Ice_ThicknessField;
            }
            set {
                this.mean_Solid_Ice_ThicknessField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Mean_Solid_Ice_ThicknessSpecified {
            get {
                return this.mean_Solid_Ice_ThicknessFieldSpecified;
            }
            set {
                this.mean_Solid_Ice_ThicknessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Mean_WS_Btm_Of_Ice {
            get {
                return this.mean_WS_Btm_Of_IceField;
            }
            set {
                this.mean_WS_Btm_Of_IceField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Mean_WS_Btm_Of_IceSpecified {
            get {
                return this.mean_WS_Btm_Of_IceFieldSpecified;
            }
            set {
                this.mean_WS_Btm_Of_IceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Mean_WS_Btm_Of_Slush {
            get {
                return this.mean_WS_Btm_Of_SlushField;
            }
            set {
                this.mean_WS_Btm_Of_SlushField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Mean_WS_Btm_Of_SlushSpecified {
            get {
                return this.mean_WS_Btm_Of_SlushFieldSpecified;
            }
            set {
                this.mean_WS_Btm_Of_SlushFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Mean_Meas_T {
            get {
                return this.mean_Meas_TField;
            }
            set {
                this.mean_Meas_TField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Mean_Meas_TSpecified {
            get {
                return this.mean_Meas_TFieldSpecified;
            }
            set {
                this.mean_Meas_TFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Mean_Ang_Cf {
            get {
                return this.mean_Ang_CfField;
            }
            set {
                this.mean_Ang_CfField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Mean_Ang_CfSpecified {
            get {
                return this.mean_Ang_CfFieldSpecified;
            }
            set {
                this.mean_Ang_CfFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class XmlRootSummaryStation {
        
        private decimal stn_QField;
        
        private bool stn_QFieldSpecified;
        
        private decimal percent_TotField;
        
        private bool percent_TotFieldSpecified;
        
        private string start_TField;
        
        private decimal meas_TField;
        
        private bool meas_TFieldSpecified;
        
        private decimal percent_GoodField;
        
        private bool percent_GoodFieldSpecified;
        
        private decimal avg_VField;
        
        private bool avg_VFieldSpecified;
        
        private decimal cvField;
        
        private bool cvFieldSpecified;
        
        private decimal dir_VField;
        
        private bool dir_VFieldSpecified;
        
        private decimal distField;
        
        private bool distFieldSpecified;
        
        private decimal depthField;
        
        private bool depthFieldSpecified;
        
        private decimal widthField;
        
        private bool widthFieldSpecified;
        
        private decimal areaField;
        
        private bool areaFieldSpecified;
        
        private decimal ang_CfField;
        
        private bool ang_CfFieldSpecified;
        
        private decimal aDCP_DepthField;
        
        private bool aDCP_DepthFieldSpecified;
        
        private decimal wS_Btm_Of_SlushField;
        
        private bool wS_Btm_Of_SlushFieldSpecified;
        
        private decimal wS_Btm_Of_IceField;
        
        private bool wS_Btm_Of_IceFieldSpecified;
        
        private decimal solid_Ice_ThicknessField;
        
        private bool solid_Ice_ThicknessFieldSpecified;
        
        private decimal slush_AreaField;
        
        private bool slush_AreaFieldSpecified;
        
        private decimal perc_SlushField;
        
        private bool perc_SlushFieldSpecified;
        
        private string idField;
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Stn_Q {
            get {
                return this.stn_QField;
            }
            set {
                this.stn_QField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Stn_QSpecified {
            get {
                return this.stn_QFieldSpecified;
            }
            set {
                this.stn_QFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Percent_Tot {
            get {
                return this.percent_TotField;
            }
            set {
                this.percent_TotField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Percent_TotSpecified {
            get {
                return this.percent_TotFieldSpecified;
            }
            set {
                this.percent_TotFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Start_T {
            get {
                return this.start_TField;
            }
            set {
                this.start_TField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Meas_T {
            get {
                return this.meas_TField;
            }
            set {
                this.meas_TField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Meas_TSpecified {
            get {
                return this.meas_TFieldSpecified;
            }
            set {
                this.meas_TFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Percent_Good {
            get {
                return this.percent_GoodField;
            }
            set {
                this.percent_GoodField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Percent_GoodSpecified {
            get {
                return this.percent_GoodFieldSpecified;
            }
            set {
                this.percent_GoodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Avg_V {
            get {
                return this.avg_VField;
            }
            set {
                this.avg_VField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Avg_VSpecified {
            get {
                return this.avg_VFieldSpecified;
            }
            set {
                this.avg_VFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CV {
            get {
                return this.cvField;
            }
            set {
                this.cvField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool CVSpecified {
            get {
                return this.cvFieldSpecified;
            }
            set {
                this.cvFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Dir_V {
            get {
                return this.dir_VField;
            }
            set {
                this.dir_VField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Dir_VSpecified {
            get {
                return this.dir_VFieldSpecified;
            }
            set {
                this.dir_VFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Dist {
            get {
                return this.distField;
            }
            set {
                this.distField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool DistSpecified {
            get {
                return this.distFieldSpecified;
            }
            set {
                this.distFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Depth {
            get {
                return this.depthField;
            }
            set {
                this.depthField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool DepthSpecified {
            get {
                return this.depthFieldSpecified;
            }
            set {
                this.depthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool WidthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool AreaSpecified {
            get {
                return this.areaFieldSpecified;
            }
            set {
                this.areaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Ang_Cf {
            get {
                return this.ang_CfField;
            }
            set {
                this.ang_CfField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Ang_CfSpecified {
            get {
                return this.ang_CfFieldSpecified;
            }
            set {
                this.ang_CfFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ADCP_Depth {
            get {
                return this.aDCP_DepthField;
            }
            set {
                this.aDCP_DepthField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool ADCP_DepthSpecified {
            get {
                return this.aDCP_DepthFieldSpecified;
            }
            set {
                this.aDCP_DepthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WS_Btm_Of_Slush {
            get {
                return this.wS_Btm_Of_SlushField;
            }
            set {
                this.wS_Btm_Of_SlushField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool WS_Btm_Of_SlushSpecified {
            get {
                return this.wS_Btm_Of_SlushFieldSpecified;
            }
            set {
                this.wS_Btm_Of_SlushFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WS_Btm_Of_Ice {
            get {
                return this.wS_Btm_Of_IceField;
            }
            set {
                this.wS_Btm_Of_IceField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool WS_Btm_Of_IceSpecified {
            get {
                return this.wS_Btm_Of_IceFieldSpecified;
            }
            set {
                this.wS_Btm_Of_IceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Solid_Ice_Thickness {
            get {
                return this.solid_Ice_ThicknessField;
            }
            set {
                this.solid_Ice_ThicknessField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Solid_Ice_ThicknessSpecified {
            get {
                return this.solid_Ice_ThicknessFieldSpecified;
            }
            set {
                this.solid_Ice_ThicknessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Slush_Area {
            get {
                return this.slush_AreaField;
            }
            set {
                this.slush_AreaField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Slush_AreaSpecified {
            get {
                return this.slush_AreaFieldSpecified;
            }
            set {
                this.slush_AreaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlElement(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Perc_Slush {
            get {
                return this.perc_SlushField;
            }
            set {
                this.perc_SlushField = value;
            }
        }
        
        /// <remarks/>
        [XmlIgnore()]
        public bool Perc_SlushSpecified {
            get {
                return this.perc_SlushFieldSpecified;
            }
            set {
                this.perc_SlushFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
}
